<a href="https://colab.research.google.com/github/SahuRicha435/explore/blob/main/NUMPY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [ ]:
# 0D array

import numpy as np
arr = np.array(42)
print(arr)


42


In [ ]:
# 1d array

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [ ]:
# 2d array

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
# 3d array

import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np

a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as  np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row :',arr[0,1])

2nd element on 1st row : 2


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (arr[0,1,2])

6


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print ('last element from 2nd dim:',arr[1,-1])

last element from 2nd dim: 10


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
# SLICING ARRAYS

import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]
